[package]
name = "logx"
version = "1.1.0"
edition = "2021"
rust-version = "1.70"
description = "Single-file logger with zero dependencies."
license = "BSD-2-Clause"
repository = "https://github.com/ka1rav6/logx"
keywords = ["log", "logger", "logging", "single-file"]
categories = ["development-tools::debugging"]

[lib]
name = "logx"
path = "logx.rs"
